### ISSUE TITLE
TASK-8: Check session annotation

### ISSUE THREAD

**Issue by avdeev1** [Star-Trello-Tracker/Dark-Side#16]
We need to write annotation, that will automatically check token and if token will invalid the annotation would send 401 status.

For example:
```java
@PostMapping("/edit")
@CheckAuth(@RequestHeader("Authorization") String token) // My annotation
public ResponseEntity<?> updateUserProfile(
          User user,
          @RequestBody EditingProfileDto editingProfile
) {
    return userService.updateUserProfile(user, editingProfile);
}
```

If token is invalid, annotation would send to front 401 status, else it would send current user to controller.

**Comment by olli2017** [comment]
I think we close it with filter. Anno not necessary. auth need in all URLs without login, register
